@startuml
set namespaceSeparator .


class geometry.Point  {
  x : FLOAT
  y : FLOAT
  z : FLOAT
}


class geometry.Translation  {
  x : FLOAT
  y : FLOAT
  z : FLOAT
}


class geometry.Rotation  {
  yaw : FLOAT
  pitch : FLOAT
  roll : FLOAT
}


class geometry.Transformation  {
}


class geometry.Pose  {
}


class geometry.Shape <<abstract>> {
}


class geometry.ComplexShape  {
}


class geometry.PredefinedShape <<abstract>> {
}


class geometry.Circle  {
  radius : FLOAT
}


class geometry.Square  {
  length : FLOAT
}


class geometry.Rectangle  {
  width : FLOAT
  length : FLOAT
}


class geometry.Cylinder  {
  radius : FLOAT
  height : FLOAT
}


class geometry.ArbitraryShape  {
}


geometry.Transformation *--> geometry.Translation: translation
geometry.Transformation *--> geometry.Rotation: rotation
geometry.Pose *--> geometry.Translation: translation
geometry.Pose *--> geometry.Rotation: rotation
geometry.Shape <|-- geometry.PredefinedShape
geometry.Shape <|-- geometry.ArbitraryShape
geometry.Shape <|-- geometry.ComplexShape
geometry.ComplexShape *--> geometry.Shape: shapes 0..*
geometry.PredefinedShape <|-- geometry.Circle
geometry.PredefinedShape <|-- geometry.Square
geometry.PredefinedShape <|-- geometry.Rectangle
geometry.PredefinedShape <|-- geometry.Cylinder
geometry.ArbitraryShape *--> geometry.Point: points 0..*
@enduml
