@startuml
set namespaceSeparator .


class networking.Networking  {
}


class networking.NetworkTopology  {
  name : ID
}


class networking.N2NConnection  {
}


class networking.Network <<abstract>> {
}


class networking.WiredNetwork  {
  name : ID
  subnet : STRING
  gateway : STRING
  dhcp : BOOL
  dns : optional<list[STRING]>
}


class networking.WirelessNetwork  {
  name : ID
  wifi_ssid : STRING
  psk : STRING
  ip : STRING
  subnet : STRING
  gateway : STRING
  dns : optional<list[NID]>
}


class networking.Import  {
  importURI : FQNI
  name : ID
}


networking.Networking *--> networking.Network: networks 0..*
networking.Networking *--> networking.NetworkTopology: topology
networking.NetworkTopology o--> networking.Network: networks 0..*
networking.NetworkTopology *--> networking.N2NConnection: connections 0..*
networking.N2NConnection o--> networking.Network: from
networking.N2NConnection o--> networking.Network: to
networking.Network <|-- networking.WiredNetwork
networking.Network <|-- networking.WirelessNetwork

legend
  Match rules:
  |= Name  |= Rule details |
  | FQN | ID (. ID)* |
  | CommentLine | \\/\\/.*\?$ |
  | Description | \\#(.*\?)$ |
  | FQNI | (ID)+ .*\? |
  | CommentBlock | \\/\\*(.\|\\n)*\?\\*\\/ |
  | NID | (.*\?)\\n |
  | Comment |  |
end legend

@enduml
