Package {
  name: objects
}

DataType EmptyObject { }

DataType Header {
  # Message Header
  timestamp: int
  seq: int
  node_id: str
}

DataType SonarData {
  # Sonar Sensor Data Model
  range: float
  hfov: float
  vfov: float
}

DataType ToFData {
  # Time-of-Flight (ToF) Sensor Data Model
  range: float
  hfov: float
  vfov: float
}

DataType LiDARData {
  data: float[]
  header: Header
}

DataType RangeSensorData {
  # Time-of-Flight (ToF) Sensor Data Model
  range: float
  hfov: float
  vfov: float
}

Enum SensorState {
    'ENABLED'
    'DISABLED'
    'HALTED'
    'RUNNING'
    'STOPPED'
    'INTERNAL_ERROR'
    'NOT_CONNECTED'
}
